### ISSUE TITLE
Could not build with cargo

### ISSUE THREAD

**Issue by yillkid** [iotaledger/MAM#11]
`ubuntu@devorg:~/MAM$ cargo build --all --release --verbose
warning: unused manifest key: dependencies.iota-curl.iota-curl-cpu.path
    Updating git repository `https://github.com/iotaledger/iota.rs`
    Updating git repository `https://github.com/japaric/cty.git`
       Fresh cty v0.1.5 (https://github.com/japaric/cty.git#40007c54)
   Compiling iota-trytes v0.1.0 (https://github.com/iotaledger/iota.rs#9fcdfc1f)
     Running `rustc --crate-name iota_trytes /home/ubuntu/.cargo/git/checkouts/iota.rs-1792f679be51837c/9fcdfc1/trytes/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="alloc"' -C metadata=74bced331196adde -C extra-filename=-74bced331196adde --out-dir /home/ubuntu/MAM/target/release/deps -L dependency=/home/ubuntu/MAM/target/release/deps --cap-lints allow`
error[E0432]: unresolved import `alloc::string::String`
 --> /home/ubuntu/.cargo/git/checkouts/iota.rs-1792f679be51837c/9fcdfc1/trytes/src/string.rs:2:5
  |
2 | use alloc::string::String;
  |     ^^^^^^^^^^^^^^^^^^^^^ Could not find `string` in `alloc`

error[E0554]: #[feature] may not be used on the stable release channel
 --> /home/ubuntu/.cargo/git/checkouts/iota.rs-1792f679be51837c/9fcdfc1/trytes/src/lib.rs:2:43
  |
2 | #![cfg_attr(any(feature = "alloc", test), feature(alloc))]
  |                                           ^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `iota-trytes`.

Caused by:
  process didn't exit successfully: `rustc --crate-name iota_trytes /home/ubuntu/.cargo/git/checkouts/iota.rs-1792f679be51837c/9fcdfc1/trytes/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg feature="default" --cfg feature="alloc" -C metadata=74bced331196adde -C extra-filename=-74bced331196adde --out-dir /home/ubuntu/MAM/target/release/deps -L dependency=/home/ubuntu/MAM/target/release/deps --cap-lints allow` (exit code: 101)`

**Comment by th0br0** [comment]
Hey! Please use a nightly compiler. The core iota.rs crates run fine without (except for bindings) but I'm afraid that mam depends on nightly for now.
